### ISSUE TITLE
Support Reading Flatbuffers as Input

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/PotreeConverter#1]
In order to directly process the output of LogParser, we want to PotreeConverter to support reading flatbuffer files as input.

**Comment by kkrishnan-nd** [comment]
The flatbuffer file (.lidar) can be read by the potreeconverter now and can be rendered to the right Potree format. 
![fb](https://user-images.githubusercontent.com/43177711/48216198-04135780-e352-11e8-857f-849ddc241f6f.png)
The above figure is the reading , converting and writing process from flatbuffer file. 

![fb2](https://user-images.githubusercontent.com/43177711/48216237-1beadb80-e352-11e8-8d9d-2d65d02c9ec9.png)
This proves the rendering of fb files. Although the dataset wasnt quite time synced. The code do perform well Now. 
 


The changes are available in the Flatbuffer-reader branch

**Comment by kkrishnan-nd** [comment]
git branch `flatbuffer-reader` of potreeconverter can now convert rotation applied bbox tracks (with sys argument  `-b` ) and also point cloud (without any sys argument). 

Below is the output screenshot of rotated track bounding box.
![rotated_boundingbox_fb](https://user-images.githubusercontent.com/43177711/48642126-f55c1e80-e9a9-11e8-93f3-fd004076fdf2.png)

Below if the output screenshot of points.
![katri](https://user-images.githubusercontent.com/43177711/48642174-1886ce00-e9aa-11e8-97c8-a0ef4f10ba55.png)


![out](https://user-images.githubusercontent.com/43177711/48642254-4835d600-e9aa-11e8-9611-fdf5d22a8794.png)

**Comment by kkrishnan-nd** [comment]
Now the code takes a sys argument `-b "point"` for reading flat buffer points and `-b "bbox"` for reading bounding box points

**Comment by vrajur-nd** [comment]
closed.
