### ISSUE TITLE
Octree bounding box calc is run multiple times during conversion

### ISSUE THREAD

**Issue by dgandhiAM** [NextDroid/PotreeConverter#20]
In order to create the POTree octree, the converter requires a prior -- the maximal bounding box of the point cloud.  The converter determines this by first running through all the points in the cloud.  This calculation is run in the constructor of the flatbuffer reader, which gets created (and destroyed) at least twice, resulting in superfluous runs through the point cloud.

The first call stems from here:
https://github.com/NextDroid/PotreeConverter/blob/406d2343bebb756638483d61fb88e4027071b661/PotreeConverter/src/PotreeConverter.cpp#L348

The second call stems from here:
https://github.com/NextDroid/PotreeConverter/blob/406d2343bebb756638483d61fb88e4027071b661/PotreeConverter/src/PotreeConverter.cpp#L401

**Comment by dgandhiAM** [comment]
I assigned this to @vrajur-nd to keep track of this issue, but we can reassign to @jallen-NextDroid or someone else during the next retro to actually execute .

**Comment by vrajur-nd** [comment]
Complete - see #23
