### ISSUE TITLE
Merge upstream PotreeConverter with our fork

### ISSUE THREAD

**Issue by nmhaddadND** [NextDroid/PotreeConverter#27]
PotreeConverter has been updated to version 2.0, which is much faster, produces only 3 files instead of tens of millions, and includes a number of other upgrades. 

However, it is a complete rewrite. It also costs money this time around (pricing uncertain).

Merging these two would take a lot of effort, but it seems to be worth it. In merging, we should consider abstracting our stuff out into our own directories and files so that it is easier to merge in the future.

**Comment by nmhaddadND** [comment]
Basis for the new POTreeConverter 2.0
https://www.cg.tuwien.ac.at/research/publications/2020/SCHUETZ-2020-MPC/

**Comment by dgandhiAM** [comment]
@nmhaddadND Investigate what we're missing on POTreeConverter 1.7 so we can decide what to do in terms of interim upstream merges.

**Comment by nmhaddadND** [comment]
I looked into this. Other than many, many bug fixes, there are no significant improvements to performance. Many of the bug fixes are for specific use cases, reported by users of PotreeConverter who documented their issues. The version releases mostly clean up code, documentation, and fix other small bugs. @arjunskND @bcasselsND @dgandhiAM

**Comment by nmhaddadND** [comment]
@bcasselsND contact info for Potree:

Markus Schütz
mschuetz@potree.org

https://github.com/potree/potree
https://github.com/potree/PotreeConverter

# Pricing
You can evaluate PotreeConverter for free for three months before you need to purchase a license. Licenses are per simultaneously running instance of PotreeConverter 2.0. The licensee can install PotreeConverter on multiple devices of the licensee, but only keep one instance of the converter running at a time.

240€ per instance for a perpetual license of the software at the date of purchase, plus one year of updates.
1200€ per instance and year for fully automated SaaS hosting services that include PotreeConverter. This applies to online services that provide customers a platform to upload their data, which is then automatically processed by a converter instance, and finally made available online publicly or behind authentication (e.g. youtube or sketchfab for point clouds).
Anyone who has donated to or funded Potree before August 2020 is considered to have a perpetual license under bullet point [1], plus additional numbers of [1] or [2] that match the amount of donation/funding.
Note that this only applies to the licensee using PotreeConverter 2.0. You're allowed to convert your customers data with PotreeConverter 2.0 and host it online via Potree 1.7(free), without the need to aquire additional licenses for customers. You're also allowed to distribute converted data via PotreeDesktop 1.7 without the need for additional licenses. The customer will only need to purchase licenses if they decide to convert point cloud data with the converter themselves.
If in doubt, just start using it for the three month trial period and ask for clarifications via licensing@potree.org
Licensees will have priority support. I'll reply to smaller issues as fast as possible, and offer support plans for larger issues.
Licenses can be purchased with following options:

Paypal (with volume licenses)
Github Sponsorship, see "Sponsor" button at the top. (monthly single license)
Via invoice and wire transfer - contact licensing@potree.org

**Comment by dgandhiAM** [comment]
@bcasselsND will contact potree team about how licensing will be structured for Veritas use

**Comment by dgandhiAM** [comment]
Different approach -- writing new code into potreeconv 2.0. Deprecated.
