### ISSUE TITLE
Output flag segfaults on flatbuffer reader

### ISSUE THREAD

**Issue by kkrishnan-nd** [NextDroid/PotreeConverter#3]
We need to find out if this due to one of our changes or an issue with the original PotreeConverter code.

**Comment by vrajur-nd** [comment]
This is old and low priority, since we work around this by not specifying an output flag in our processing pipeline and moving things manually.

**Comment by dgandhiAM** [comment]
@jallen-NextDroid Check this out... figure out current status.

**Comment by dgandhiAM** [comment]
@jallen-NextDroid this continues to be an issue. Rather than specifying an output flag, we move the output to the correct location via runengine after the fact. Not ideal.
